- name: Rabbitmq setup
  hosts: all
  become: yes
  tasks:
    - name: Install Erlang
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: Install Rabbitmq Server
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: Rabbitmq Server
      ansible.builtin.yum:
        name: rabbitmq-server
        state: installed

    - name: Restart Rabbitmq
      ansible.builtin.systemd:
        name: rabbitmq-server
        state: restarted
        enabled: yes

    - name: Add Application User
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: Roboshop@1
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present

