- name: MySQL Repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL
  ansible.builtin.shell: yum module disable mysql -y

- name: Install mysql community server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Restart MySQL
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Set root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass Roboshop@1